version: "3"
services:
  altv-openrp:
    build: 
      context: .
      args:
        - SERVER_NAME='Dockerized Open RP'
        - SERVER_DESCRIPTION='Demonstration Purposes Only'
        - SERVER_PLAYERS=64
        - SERVER_ANNOUNCE=false
        - SERVER_TOKEN=''
        - SERVER_WEBSITE='twitch.tv/stuykgaming'
        - SERVER_LANGUAGE=en
        - SERVER_DEBUG=true
        - SERVER_STREAMINGDISTANCE=300
        - SERVER_PASSWORD=''
        - DISCORD_URL=
        - DISCORD_TOKEN=
        - ALTV_VERSION=beta
    image: altv-openrp:latest
    container_name: altv-openrp
    ports:
      - "7788:7788"
      - "7788:7788/udp"
    depends_on:
      - db
  db:
    image: "postgres:11"
    container_name: db
    environment:
      - POSTGRES_DB=altv
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: